# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
# Change $SCRIPT_DIR to the location of your scripts!
command=/home/faust/.config/i3/scripts/$BLOCK_NAME
separator_block_width=10
markup=none
#color=#DCDCDC

[packages]
command=/home/faust/.config/i3/scripts/packages
label=P
interval=3
#separator=false

#[apt-upgrades]
#command=/home/faust/.config/i3/scripts/apt-upgrades
#signal=1
#interval=3600
#interval=1
#PENDING_SYMBOL="\uf021 "
#SYMBOL_ONLY=0
#ALWAYS_PRINT=1
#PENDING_COLOR="#00FF00"
#NONPENDING_COLOR="#FFFFFF"

#[dunst]
#command= ~/.config/i3/scripts/notify
#signal=12

[ping]
command=/home/faust/.config/i3/scripts/ping
#label= 
interval=5
#separator=false

# Network interface and VPN monitoring
#
# If the instance is not specified, use the interface used for default route.
# The address can be forced to IPv4 or IPv6 with -4 or -6 switches.
# Support multiple VPN, with colors.
#[ping]
#command=/home/faust/.config/i3/scripts/ping
#label=
#interval=5

[memory]
command=/home/faust/.config/i3/scripts/memory
#label=
interval=30

[disk]
command=/home/faust/.config/i3/scripts/disk -f " {pused}%" -tc '{pfree}' '<' 20 -tc '{pfree}' '<' 10
instance=/home/faust
interval=3600

[temperature]
command=/home/faust/.config/i3/scripts/temperature
#label=TEMP
#label=
interval=5
#T_WARN=70
#T_CRIT=90
#SENSOR_CHIP=""

[dunst]
command=/home/faust/.config/i3/scripts/dunst
interval=once
format=json
markup=pango
#min_width=50
#align=center
#DUNST_MUTE=off

[volume]
command=/home/faust/.config/i3/scripts/volume -f "{icon} {volume}%" -id "" -im "" -fe '{port}' '=' 'headphone' '{icon}  {volume}%' -fe '{dev_bus}' '=' 'bluetooth' '{icon}  {volume}%' -tw '{muted}' '=' 'yes'
markup=pango
interval=1

# Battery indicator
[battery]
command=/home/faust/.config/i3/scripts/battery
markup=pango
interval=5

[kbd]
interval=1
command=xset -q|grep LED| awk '{ if (substr ($10,5,1) == 1) print "RU"; else print "EN"; }'

#[kbdd_layout]
#command=/home/faust/.config/i3/scripts/kbdd_layout
#interval=persist

#[time]
#command= date '+%H:%M'
#interval=5
#label=
#color=#DCDCDC

[rofi-calendar]
command=/home/faust/.config/i3/scripts/rofi-calendar
interval=5
#LABEL=
DATEFTM=+%a. %d. %b. %Y
SHORTFTM=+%d.%m.%Y
